# Generated by Django 6.0 on 2025-12-31 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('industry_type', models.CharField(choices=[('Mining', 'Mining'), ('Metallurgy', 'Metallurgy')], max_length=50)),
                ('material', models.CharField(max_length=50)),
                ('process_stage', models.CharField(max_length=50)),
                ('energy_consumption', models.FloatField(help_text='in kWh')),
                ('water_usage', models.FloatField(help_text='in Liters')),
                ('raw_material_qty', models.FloatField(help_text='in Tons')),
                ('carbon_footprint', models.FloatField(blank=True, null=True)),
                ('circularity_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
